using System;
using System.Collections.Generic;

namespace CvBuilder.Models
{
    public class Language
    {
        public int LanguageId { get; set; } // Auto-generated by the database
        public string LanguageName { get; set; } = string.Empty;
        public string ProficiencyLevel { get; set; } = string.Empty;

        public int ResumeId { get; set; }
        public Resume? Resume { get; set; }

        public Language()
        {
            LanguageName = string.Empty;
            ProficiencyLevel = string.Empty;
        }

        public Language(string languageName, string proficiencyLevel, Resume resume)
        {
            if (string.IsNullOrWhiteSpace(languageName))
                throw new ArgumentException("Language name cannot be empty.", nameof(languageName));

            if (string.IsNullOrWhiteSpace(proficiencyLevel))
                throw new ArgumentException("Proficiency level cannot be empty.", nameof(proficiencyLevel));

            LanguageName = languageName;
            ProficiencyLevel = proficiencyLevel;
            Resume = resume ?? throw new ArgumentNullException(nameof(resume));
            ResumeId = resume.ResumeId;
        }
    }
}