using System;
using System.Collections.Generic;

namespace CvBuilder.Models
{
    public class Skill
    {
        public int SkillId { get; set; } // Auto-generated by the database
        public string SkillName { get; set; } = string.Empty;
        public int ResumeId { get; set; }
        public Resume? Resume { get; set; }

        public Skill() 
        {
            SkillName = string.Empty;
        } 

        public Skill(string skillName, Resume resume)
        {
            if (string.IsNullOrWhiteSpace(skillName))
                throw new ArgumentException("Skill name cannot be empty.", nameof(skillName));

            SkillName = skillName;
            Resume = resume ?? throw new ArgumentNullException(nameof(resume));
            ResumeId = resume.ResumeId;
        }
    }
}