using System;
using System.Collections.Generic;

namespace CvBuilder.Models
{
    public class WorkExperience
    {
        public int WorkExperienceId { get; set; } // Auto-generated by the database
        public required string JobTitle { get; set; }
        public required string Employer { get; set; }
        public required string City { get; set; }
        public required DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; } 
        public required string Description { get; set; }

        public int ResumeId { get; set; }
        public Resume? Resume { get; set; }

        public string StartDateFormatted => StartDate.ToString("yyyy-MM");
        public string EndDateFormatted => EndDate?.ToString("yyyy-MM") ?? "Present";

        public WorkExperience() { } // Parameterless constructor required by EF Core

        public WorkExperience(string jobTitle, string employer, string city, DateTime startDate, DateTime? endDate, string description, int resumeId)
        {
            if (string.IsNullOrWhiteSpace(jobTitle))
                throw new ArgumentException("Job title cannot be empty.", nameof(jobTitle));

            if (string.IsNullOrWhiteSpace(employer))
                throw new ArgumentException("Employer cannot be empty.", nameof(employer));

            if (string.IsNullOrWhiteSpace(city))
                throw new ArgumentException("City cannot be empty.", nameof(city));

            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description cannot be empty.", nameof(description));

            if (endDate.HasValue && endDate < startDate)
                throw new ArgumentException("End date cannot be earlier than start date.");

            JobTitle = jobTitle;
            Employer = employer;
            City = city;
            StartDate = startDate;
            EndDate = endDate;
            Description = description;
            ResumeId = resumeId; // Only store the foreign key
        }
    }
}